### ISSUE TITLE
Domain models: 2.1.3 Method names - Only real getters should be named get*

### ISSUE THREAD

**Issue by fvosberg** [oliverklee/workshop-handouts#78]
Hi Oliver,

thanks for your nice compilation of best practices. I totally agree with the most of the stuff and it's great to be reminded of some parts ;).

But I totally not agree with some point you've made. You say that you don't want methods "with logic" called get*. I think that you want that, because when you call the method and it starts with get you don't have to consider any orthogonal state changes. You "are sure to only get something". Is that right? 

I don't agree with that because of the principle of "Information Hiding" of OOP. (Not because of the principle itself, but it's advantages ;)). Let's consider you have a plain getter for an attribute price. It just returns the price attribute of the Product object. In version two you are going to implement some taxes logic. So you want to calculate taxes for different product categories in the prior plain getter. So getPrice gets logic which depends on internal state. Do you want the API to change for that? That would cause strong coupleing of the API to its implementation. Should the caller of a method really consider it's implementation?

Just some thoughts, maybe I'm getting your point wrong or you have some other examples in mind. 

I'm curious about your answers

**Comment by oliverklee** [comment]
1.  First of all, I completely agree that e.g., in your use case, there should be a method on the object to get/retrieve the price. This method and the secret knowledge how the price is calculated totally belong in the model class, and the callers shouldn't need to know.
2. get* for a method name is very generic. If we don't need this particular naming schema (e.g., because the property is accessed in a fluid template), I recommend using more specific names like calculate*, retrieve* so that the name conveys more information about what exactly the method does. (One of the podcasts I listen to had this as a topic in an episode on clean code. I think it was http://www.se-radio.net/2017/01/se-radio-episode-280-gerald-weinberg-on-bugs-errors-and-software-quality/ , but I'm not quite sure, and I would like to avoid listening to that episode again.)
3. What I recommend against are methods that are named "get*", but that do more than just "read properties and maybe combine them in some way".

So my guess is that we agree on this, but the wording is misleading.

Would you be willing to create a PR to improve the wording and explain the rationales?

**Comment by fvosberg** [comment]
Thanks for your fast reply. Yes, I think we are complete in agreement, but the wording could be a little improved to not mislead others in some use cases. I'm going to create a PR with my point of view this weekend.

Looking forward to your opinions on my draft.

**Comment by oliverklee** [comment]
Great, thanks! ❤️
